In [1]:
# import packages with alias
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
array1 = np.array([1,2,3])
array1.shape

(3,)

In [6]:
matrix1 = np.array([[1,2], [4,5], [7,8]])
matrix1.shape

(3, 2)

In [10]:
matrix1 = np.reshape(matrix1, (6,))
matrix1

array([1, 2, 4, 5, 7, 8])

In [11]:
matrix1*5 # note similarity to R vector multiplication

array([ 5, 10, 20, 25, 35, 40])

In [14]:
# dot product
x = np.array([1,1,1])
y = np.array([0,2,1])
np.dot(x, y)

3

In [16]:
matrix2 = np.random.randn(3,5)
matrix2

array([[-0.39636819, -0.61997662,  1.28270543,  0.4489389 ,  0.1508279 ],
       [ 0.16881084,  1.13725452,  0.29083287,  1.85644194,  0.75980711],
       [ 1.64217361, -0.71042174, -1.02561048, -0.0268194 ,  3.31907587]])

In [18]:
data_table = pd.DataFrame(matrix2)
data_table

0         1         2         3         4
0 -0.396368 -0.619977  1.282705  0.448939  0.150828
1  0.168811  1.137255  0.290833  1.856442  0.759807
2  1.642174 -0.710422 -1.025610 -0.026819  3.319076

In [19]:
data_table.columns = ["c1", "c2", "c3", "c4", "c5"]
data_table

c1        c2        c3        c4        c5
0 -0.396368 -0.619977  1.282705  0.448939  0.150828
1  0.168811  1.137255  0.290833  1.856442  0.759807
2  1.642174 -0.710422 -1.025610 -0.026819  3.319076

In [20]:
data_table["c1"]

0   -0.396368
1    0.168811
2    1.642174
Name: c1, dtype: float64

In [22]:
data_table.describe()

c1        c2        c3        c4        c5
count  3.000000  3.000000  3.000000  3.000000  3.000000
mean   0.471539 -0.064381  0.182643  0.759520  1.409904
std    1.052448  1.041629  1.157955  0.979293  1.681195
min   -0.396368 -0.710422 -1.025610 -0.026819  0.150828
25%   -0.113779 -0.665199 -0.367389  0.211060  0.455318
50%    0.168811 -0.619977  0.290833  0.448939  0.759807
75%    0.905492  0.258639  0.786769  1.152690  2.039441
max    1.642174  1.137255  1.282705  1.856442  3.319076